# Generated by Django 4.2.1 on 2023-06-10 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=30)),
                ('Slug', models.SlugField(max_length=30, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Card_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_photo', models.ImageField(blank=True, upload_to='images/')),
                ('Product_name', models.CharField(max_length=30)),
                ('Product_description', models.TextField(max_length=100)),
                ('Product_created_time', models.DateTimeField(auto_now_add=True)),
                ('Product_last_update', models.DateTimeField(auto_now=True)),
                ('Product_published', models.BooleanField(default=True)),
                ('Slug', models.SlugField(max_length=30, verbose_name='URL')),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cool_Site.card_category')),
            ],
        ),
    ]
